package com.company.exceptionHandling;

public class Question1 {

//    public void arithmetic() throws ArithmeticException().initCause(new Throwable("nullPointerException"))
    {
    }
}
//    public static void main(String[] args) {
//        try {
//            int a = 45;
//            int b = 0 ;
//            int c = a/b;
//        }
//        catch(ArithmeticException e) {
//            e.printStackTrace();
//            System.out.println("Arithmatic Exception");
//            try {
//                String string = null;
//                string.length();
//            }
//            catch (NullPointerException ex) {
//                e.printStackTrace();
//                System.out.println("Null Pointer Exception");
//            }
//
//        }
//    }


